### ISSUE TITLE
Kong Summit Hackathon 2021

### ISSUE THREAD

**Issue by falondarville** [scottharwell/insomnia-plugin-oci-auth#1]
Hi @scottharwell, I'm the tech writer for Insomnia. The team noticed that your plugin was submitted during the timeframe for the Kong Summit Hackathon. We'd love to have you submit it for a T-shirt and possible prize here: https://konghq.com/summit-hackathon/.

**Comment by scottharwell** [comment]
Thanks @falondarville for letting me know.  I submitted the hackathon entry.
